[package]
name = "crud-bench"
edition = "2021"
version = "0.1.0"
license = "Apache-2.0"
readme = "README.md"

[features]
default = ["redis", "rocksdb", "postgres", "mongodb", "surrealkv", "surrealdb"]
redis = ["dep:redis"]
mongodb = ["dep:mongodb"]
rocksdb = ["dep:rocksdb"]
postgres = ["dep:tokio-postgres"]
surrealdb = ["dep:surrealdb"]
surrealkv = ["dep:surrealkv"]

[profile.release]
lto = true
strip = true
opt-level = 3
panic = 'abort'
codegen-units = 1

[dependencies]
anyhow = "1.0.88"
clap = { version = "4.5.17", features = ["derive"] }
env_logger = "0.11.5"
log = "0.4.22"
mongodb = { version = "2.8.2", optional = true }
rand = { version = "0.8.5", features = ["small_rng"] }
rayon = "1.10.0"
redis = { version = "0.24.0", features = ["tokio-comp"], optional = true }
rocksdb = { git = "https://github.com/surrealdb/rust-rocksdb", features = ["lz4", "snappy"], optional = true }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
surrealdb = { version = "2.0.1", optional = true }
surrealkv = { version = "0.3.6", optional = true }
tokio = { version = "1.40.0", features = ["macros", "time", "rt-multi-thread"] }
tokio-postgres = { version = "0.7.11", optional = true }
