name: Crud-bench

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  merge_group:

defaults:
  run:
    shell: bash
    working-directory: crud-bench

jobs:

  format:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Check format
        run: cargo fmt --all --check

  clippy:
    name: Check clippy
    runs-on: ubuntu-latest
    steps:
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Check clippy
        run: cargo clippy --tests -- -D warnings

  test:
    name: Check tests
    runs-on: ubuntu-latest
    steps:
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Check tests
        run: cargo test

  benchmark:
    name: Benchmark ${{ matrix.description }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Dry
          - database: dry
            description: Dry
          # Redis
          - database: redis
            description: Redis
          # Postgres
          - database: postgres
            description: Postgres
          # MongoDB
          - database: mondoDB
            description: MongoDB
          # SurrealDB + Memory
          - database: surrealdb-memory
            description: SurrealDB with in-memory storage
          # SurrealDB + RocksDB
          - database: surrealdb-rocksdb
            description: SurrealDB with RocksDB storage
          # SurrealDB + SurrealKV
          - database: surrealdb-surrealkv
            description: SurrealDB with SurrealKV storage
    steps:
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Run benchmarks (10,000 samples / 3 threads)
        run: cargo run -r -- -d ${{ matrix.database }} -s 10000 -t 3

      - name: Run benchmarks (30,000 samples / 32 threads)
        run: cargo run -r -- -d ${{ matrix.database }} -s 30000 -t 32

      - name: Run benchmarks (100,000 samples / 32 threads)
        run: cargo run -r -- -d ${{ matrix.database }} -s 100000 -t 32